-- Deep-dive analysis for a model run: an on-demand, richer read of the (already
-- computed, tested-core-produced) FitSummary — written narrative + charts generated by
-- Claude via the hosted code_execution tool (sandboxed, no network access; the model
-- never touches raw customer data beyond the small FitSummary JSON it is given).
--
-- Chart images are stored as base64 data URLs directly in this column (same pattern as
-- `summary`/`quality`: clients read aggregated JSON from Postgres, never Storage
-- directly) — expected sizes are a handful of matplotlib PNGs, comfortably small enough
-- for jsonb.
alter table mmm.model_runs
  add column if not exists analysis jsonb;
